# Generated by Django 5.2.12 on 2026-03-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('ConceptID', models.AutoField(primary_key=True, serialize=False)),
                ('ConceptName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('micro_lesson', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('AttemptID', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.DateTimeField(auto_now_add=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('TotalScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('DifficultyLevel', models.CharField(max_length=50)),
                ('CorrectAnswerText', models.TextField()),
                ('Concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning_app.concept')),
                ('Lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content_app.lecturematerial')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('ResponseID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentAnswerText', models.TextField()),
                ('IsCorrect', models.BooleanField()),
                ('TimeTaken', models.IntegerField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning_app.question')),
            ],
        ),
    ]
