# Generated by Django 5.2.12 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='IsAIGenerated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='IsPublished',
            field=models.BooleanField(default=False),
        ),
    ]
