# Generated by Django 5.2.12 on 2026-04-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_question_publish_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('ClassroomID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('JoinCode', models.CharField(db_index=True, max_length=8, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('ExpiresAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                (
                    'CreatedBy',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('IsActive', models.BooleanField(default=True)),
                ('JoinedAt', models.DateTimeField(auto_now_add=True)),
                (
                    'Classroom',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning_app.classroom'),
                ),
                (
                    'Student',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='classroomenrollment',
            constraint=models.UniqueConstraint(fields=('Classroom', 'Student'), name='uniq_classroom_student_enrollment'),
        ),
    ]
