# Generated by Django 5.2.12 on 2026-04-14

from django.db import migrations, models


def backfill_question_type(apps, schema_editor):
    Question = apps.get_model('learning_app', 'Question')
    mcq_markers = ('\na)', '\nb)', '\nc)', '\nd)', '\n1)', '\n2)', 'option a', 'option b')

    for question in Question.objects.all().only('QuestionID', 'QuestionText'):
        text = (question.QuestionText or '').lower()
        if any(marker in text for marker in mcq_markers):
            question.QuestionType = 'mcq'
        else:
            question.QuestionType = 'constructed'
        question.save(update_fields=['QuestionType'])


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_classroom_and_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='QuestionType',
            field=models.CharField(
                choices=[('mcq', 'MCQ'), ('constructed', 'Constructed-response')],
                default='constructed',
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_question_type, migrations.RunPython.noop),
    ]
