# Generated by Django 5.2.12 on 2026-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('LectureID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('FilePath', models.FileField(upload_to='lectures/')),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('SummaryID', models.AutoField(primary_key=True, serialize=False)),
                ('SummaryText', models.TextField()),
                ('IsVerified', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
