# Generated by Django 5.2.12 on 2026-03-11 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerial',
            name='UploadedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summary',
            name='Lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='content_app.lecturematerial'),
        ),
        migrations.AddField(
            model_name='summary',
            name='VerifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_summaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
