# Generated by Django 5.2.12 on 2026-03-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryValidation',
            fields=[
                (
                    'Summary',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='validation',
                        serialize=False,
                        to='content_app.summary',
                    ),
                ),
                (
                    'SummaryTextSnapshot',
                    models.TextField(),
                ),
                (
                    'IsVerified',
                    models.BooleanField(default=False),
                ),
                (
                    'CreatedAt',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'Lecture',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='summary_validations',
                        to='content_app.lecturematerial',
                    ),
                ),
                (
                    'VerifiedBy',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='summary_validation_actions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
