# Generated by Django 5.2.12 on 2026-04-01

import mimetypes
import os

from django.db import migrations, models


def backfill_file_data(apps, schema_editor):
    LectureMaterial = apps.get_model('content_app', 'LectureMaterial')

    for material in LectureMaterial.objects.all().iterator():
        file_field = getattr(material, 'FilePath', None)
        if not file_field:
            continue

        file_name = os.path.basename(file_field.name or '')
        file_path = None
        try:
            file_path = file_field.path
        except Exception:
            file_path = None

        payload = b''
        if file_path and os.path.exists(file_path):
            try:
                with open(file_path, 'rb') as handle:
                    payload = handle.read()
            except Exception:
                payload = b''

        material.OriginalFileName = file_name or material.Title
        material.FileData = payload
        material.FileSize = len(payload)
        material.MimeType = mimetypes.guess_type(file_name)[0] or ''
        material.save(update_fields=['OriginalFileName', 'FileData', 'FileSize', 'MimeType'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_summaryvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerial',
            name='FileData',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturematerial',
            name='FileSize',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturematerial',
            name='MimeType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lecturematerial',
            name='OriginalFileName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_file_data, noop_reverse),
        migrations.RemoveField(
            model_name='lecturematerial',
            name='FilePath',
        ),
    ]
